listkeeper/listkeeper/urls.py
from django.conf import settings
from django.contrib import admin, auth
from django.urls import path, include

from checklists.views import runs, templates
from directory.views import items, labels, locations
from devices import api, views as devices

urlpatterns = [
    path("", items.index),
    # Auth
    path("auth/login/", auth.views.LoginView.as_view(template_name="login.html")),
    path("auth/logout/", auth.views.LogoutView.as_view()),
    # Items
    path("items/", items.ListItems.as_view()),
    path("items/create/", items.CreateItem.as_view()),
    path("items/<int:pk>/", items.ViewItem.as_view()),
    path("items/<int:pk>/edit/", items.EditItem.as_view()),
    path("items/<int:pk>/delete/", items.DeleteItem.as_view()),
    # Devices
    path("devices/", devices.ListDevices.as_view()),
    path("devices/create/", devices.CreateDevice.as_view()),
    path("devices/<int:pk>/", devices.ViewDevice.as_view()),
    path("devices/<int:pk>/edit/", devices.EditDevice.as_view()),
    path("devices/<int:pk>/delete/", devices.DeleteDevice.as_view()),
    path("devices/<int:pk>/set-mode/<str:mode>/", devices.SetDeviceMode.as_view()),
    path("devices/<int:pk>/add-write/", devices.AddWrite.as_view()),
    path("devices/<int:pk>/add-random-write/", devices.AddRandomWrite.as_view()),
    # Locations
    path("locations/", locations.ListLocations.as_view()),
    path("locations/create/", locations.CreateLocation.as_view()),
    path("locations/reparent/", locations.ReparentLocation.as_view()),
    path("locations/<int:pk>/", locations.ViewLocation.as_view()),
    path("locations/<int:pk>/edit/", locations.EditLocation.as_view()),
    path("locations/<int:pk>/delete/", locations.DeleteLocation.as_view()),
    path("locations/<int:pk>/clear/", locations.ClearLocation.as_view()),
    # Labels
    path("labels/", labels.ListLabels.as_view()),
    path("labels/create/", labels.CreateLabel.as_view()),
    path("labels/<int:pk>/edit/", labels.EditLabel.as_view()),
    path("labels/<int:pk>/delete/", labels.DeleteLabel.as_view()),
    # Checklist templates
    path("checklists/templates/", templates.ListTemplates.as_view()),
    path("checklists/templates/create/", templates.CreateTemplate.as_view()),
    path("checklists/templates/<int:pk>/", templates.ViewTemplate.as_view()),
    path("checklists/templates/<int:pk>/json/", templates.ViewTemplate.as_view(json=True)),
    path("checklists/templates/<int:pk>/edit/", templates.EditTemplate.as_view()),
    path("checklists/templates/<int:pk>/delete/", templates.DeleteTemplate.as_view()),
    # Checklist runs
    path("checklists/runs/", runs.ListRuns.as_view()),
    path("checklists/runs/create/", runs.CreateRun.as_view()),
    path("checklists/runs/<int:pk>/", runs.ViewRun.as_view()),
    path("checklists/runs/<int:pk>/json/", runs.ViewRun.as_view(json=True)),
    path("checklists/runs/<int:pk>/post-create/", runs.PostCreateRun.as_view()),
    path("checklists/runs/<int:pk>/edit/", runs.EditRun.as_view()),
    path("checklists/runs/<int:pk>/delete/", runs.DeleteRun.as_view()),
    path("checklists/runs/<int:pk>/setup-scan/", runs.SetupScan.as_view()),
    path("checklists/runs/<int:pk>/stop-scan/", runs.StopScan.as_view()),
    # API URLs
    path("api/device/sync/", api.sync),
    # Admin delegation
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

listkeeper/devices/models.py
import datetime
import random
import urlman

from django.db import models
from django.utils import functional, timezone

from directory.models import Tag


class Device(models.Model):
    """
    A (handheld or fixed) RFID reading/writing device.
    """

    MODE_CHOICES = [
        ("passive", "Passive tracking"),
        ("assigning", "Assigning locations"),
    ]

    name = models.CharField(max_length=200, help_text="Unique-ish device name")
    type = models.CharField(max_length=200, blank=True, help_text="Device type")
    notes = models.TextField(blank=True)
    token = models.TextField(blank=True, help_text="Device API token")

    mode = models.CharField(
        max_length=32,
        choices=MODE_CHOICES,
        default=MODE_CHOICES[0][0],
        help_text="Current device mode",
    )
    location = models.ForeignKey(
        "directory.Location", blank=True, null=True, on_delete=models.SET_NULL
    )

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    last_seen = models.DateTimeField(blank=True, null=True)

    class urls(urlman.Urls):
        list = "/devices/"
        view = "{list}{self.id}/"
        edit = "{view}edit/"
        delete = "{view}delete/"
        set_assigning = "{view}set-mode/assigning/"
        set_passive = "{view}set-mode/passive/"
        add_write = "{view}add-write/"
        add_random_write = "{view}add-random-write/"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return self.urls.view

    def save(self):
        if not self.token:
            self.token = "".join(
                random.choice("23456789abcdefghkmnpqrstuvwxyz") for _ in range(32)
            )
        super().save()

    def recent_reads(self):
        """
        Returns a QuerySet of "recent" device reads to show in the UI
        """
        return self.reads.order_by("-last_seen", "tag")[:20]


class DeviceRead(models.Model):
    """
    Incoming reads of tags in the field of a device. Transient; deleted
    after a retention period. In some ways, a bad message queue.

    Devices will do some of their own buffering and de-duplication; we do not
    want to have the same tag in here once a second, though, even if they send it.
    """

    device = models.ForeignKey(
        "devices.Device", on_delete=models.CASCADE, related_name="reads"
    )
    tag = models.CharField(
        max_length=255,
        help_text="Type prefix, colon, hex value of tag (e.g. epc:f376ce13434a2b)",
    )
    item = models.ForeignKey(
        "directory.Item",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="device_reads",
    )

    created = models.DateTimeField(auto_now_add=True)
    last_seen = models.DateTimeField()
    present = models.BooleanField(default=False)
    rssi = models.FloatField(blank=True, null=True)

    class Meta:
        unique_together = [("device", "tag")]

    def __str__(self):
        return "%s seen by %s at %s" % (self.tag, self.device, self.last_seen)

    @functional.cached_property
    def directory_tag(self):
        """
        Gets the Directory Tag object that corresponds with this read, or None
        if there is not one.
        """
        try:
            return Tag.objects.select_related("item").get(id=self.tag)
        except Tag.DoesNotExist:
            return None


class DeviceWrite(models.Model):
    """
    Queue of tags to be written by a device.

    Only some devices support tag writes.
    """

    device = models.ForeignKey(
        "devices.Device", on_delete=models.CASCADE, related_name="writes"
    )
    tag = models.CharField(
        max_length=255,
        help_text="Type prefix, colon, hex value of tag (e.g. epc:f376ce13434a2b)",
    )

    created = models.DateTimeField(auto_now_add=True)

listkeeper/devices/views.py
import random
from bs4 import BeautifulSoup

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
    View,
)

from .models import Device, DeviceWrite


class ListDevices(LoginRequiredMixin, ListView):
    queryset = Device.objects.select_related("location").order_by("name")
    template_name = "devices/list.html"
    context_object_name = "devices"
    extra_context = {"section": "devices"}


class ViewDevice(LoginRequiredMixin, DetailView):
    queryset = Device.objects.prefetch_related("reads", "writes").select_related("location")
    template_name = "devices/view.html"
    extra_context = {"section": "devices"}
    patch_ids = ["device-last-seen", "recent-reads", "writes"]

    def get(self, request, *args, **kwargs):
        # Don't handle non-patch requests
        template_response = super().get(request, *args, **kwargs)
        if not request.GET.get("patch", None):
            return template_response
        # OK, they want a patch, so render the template and extract the right pieces
        template_response.render()
        soup = BeautifulSoup(template_response.content, "html.parser")
        json_response = {}
        for id in self.patch_ids:
            json_response[id] = " ".join(soup.find(id=id).decode_contents().split())
        return JsonResponse(json_response)


class EditDevice(LoginRequiredMixin, UpdateView):
    model = Device
    fields = ["name", "type", "location", "notes"]
    template_name = "generic/edit.html"
    context_object_name = "obj"
    extra_context = {"section": "devices", "noun": "device"}


class CreateDevice(LoginRequiredMixin, CreateView):
    model = Device
    fields = ["name", "type", "location", "notes"]
    template_name = "generic/create.html"
    extra_context = {"section": "devices", "noun": "device"}


class DeleteDevice(LoginRequiredMixin, DeleteView):
    model = Device
    template_name = "generic/delete.html"
    success_url = "/devices/"
    context_object_name = "obj"
    extra_context = {"section": "devices", "noun": "device"}


class SetDeviceMode(LoginRequiredMixin, DetailView):
    model = Device

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.mode = kwargs["mode"]
        self.object.save()
        return redirect(self.object.urls.view)


class AddWrite(LoginRequiredMixin, CreateView):
    model = DeviceWrite
    fields = ["device", "tag"]
    template_name = "devices/add-write.html"
    extra_context = {"section": "devices"}

    def get_initial(self):
        return {"device": self.kwargs["pk"]}

    def get_success_url(self):
        return self.object.device.urls.view


class AddRandomWrite(LoginRequiredMixin, View):
    """
    Creates a random tag to write to the device
    """

    def get(self, request, pk):
        tag_suffix = "".join(random.choice("abcdef1234567890") for i in range(22))
        self.object = DeviceWrite.objects.create(device_id=pk, tag="epc:e2%s" % tag_suffix)
        return redirect(self.object.device.urls.view)

listkeeper/templates/devices/add-write.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

    <h1>Write Tag</h1>

    <section>
        <form action="." method="POST" class="create">
            {{ form|crispy }}
            {% csrf_token %}
            <button>Write</button>
        </form>
    </section>

{% endblock content %}

listkeeper/templates/devices/list.html
{% extends "base.html" %}

{% block title %}Devices - {% endblock %}

{% block content %}

    <nav class="sub">
        <a href="/devices/create/"><i class="fa fa-plus-square" aria-hidden="true"></i> Create Device</a>
    </nav>

    <table class="list">
        <tr>
            <th>Device</th>
            <th>Mode</th>
            <th>Location</th>
            <th class="actions">Actions</th>
        </tr>
        {% for device in devices %}
        <tr class="device">
            <td class="name">
                <a href="{{ device.urls.view }}">{{ device.name }}</a>
                <small>{{ device.type }}</small>
            </td>
            <td class="mode">
                {{ device.get_mode_display }}
            </td>
            <td class="location">
                {% if device.location %}{{ device.location.name }}{% endif %}
            </td>
            <td class="actions">
                <a href="{{ device.urls.view }}" title="View"><i class="fa fa-eye" aria-hidden="true"></i></a>
                <a href="{{ device.urls.edit }}" title="Edit"><i class="fa fa-pencil" aria-hidden="true"></i></a>
            </td>
        </tr>
        {% empty %}
            <tr class="empty"><td colspan="4">No devices yet.</td></tr>
        {% endfor %}
    </table>

{% endblock content %}

listkeeper/templates/devices/view.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load humanize %}
{% load static %}

{% block extra_head %}
    <script defer src="{% static "js/device_view.js" %}"></script>
{% endblock %}

{% block title %}{{ device.name }} - Devices -{% endblock %}


{% block content %}

    <h1>{{ device.name }} <small>Device #{{ device.id }}</small></h1>

    <nav class="sub sub-light">
        {% if device.mode == "passive" %}
            <a href="{{ device.urls.set_assigning }}"><i class="fa fa-bolt" aria-hidden="true"></i> Switch to Assigning</a>
        {% else %}
            <a href="{{ device.urls.set_passive }}"><i class="fa fa-eye" aria-hidden="true"></i> Switch to Passive</a>
        {% endif %}
        <a href="{{ device.urls.add_write }}"><i class="fa fa-download" aria-hidden="true"></i> Write Tag</a>
        <a href="{{ device.urls.add_random_write }}"><i class="fa fa-download" aria-hidden="true"></i> Write Random Tag</a>
        <a href="{{ device.urls.delete }}" class="right dangerous"><i class="fa fa-trash" aria-hidden="true"></i> Delete</a>
        <a href="{{ device.urls.edit }}" class="right"><i class="fa fa-pencil" aria-hidden="true"></i> Edit</a>
    </nav>

    <section id="recent-reads">
        <h2>Recently Seen Tags</h2>
        {% for read in device.recent_reads %}
            <div class="recent-read">
                {% if read.item %}
                    <a href="{{ read.item.urls.view }}">{{ read.item.name }} <small>{{ read.tag }}</small></a>
                {% else %}
                    <a href="/items/create/?tag={{ read.tag }}" target="_blank">{{ read.tag }} <small>(no item)</small></a>
                {% endif %}
                {% if read.present %}
                    <span class="present">
                        <i class="fa fa-check" aria-hidden="true"></i> Present
                        {% if read.rssi %}<span class="rssi">{{ read.rssi|floatformat:0 }}</span>{% endif %}
                        <small>{{ read.last_seen|naturaltime }}</small>
                    </span>
                {% else %}
                    <span class="not-present">
                        <i class="fa fa-times" aria-hidden="true"></i> Not Present
                        {% if read.rssi %}<span class="rssi">{{ read.rssi|floatformat:0 }}</span>{% endif %}
                        <small>Seen {{ read.last_seen|naturaltime }}</small>
                    </span>
                {% endif %}
            </div>
        {% endfor %}
    </section>

    <section id="details">
        <h2>Details</h2>
        <dl>
            <dt>Last Seen</dt>
            <dd id="device-last-seen">
                {% if device.last_seen %}
                    {{ device.last_seen|naturaltime }}
                {% else %}
                    Never
                {% endif %}
            </dd>
            {% if device.type %}
                <dt>Type</dt>
                <dd>{{ device.type }}</dd>
            {% endif %}
            <dt>Location</dt>
            <dd>
                {% if device.location %}
                    <a href="{{ device.location.urls.view }}">{{ device.location.name }}</a>
                {% else %}
                    (none set)
                {% endif %}
            </dd>
            <dt>Mode</dt>
            <dd>{{ device.get_mode_display }}</dd>
            {% if device.notes %}
                <dt>Notes</dt>
                <dd>{{ device.notes }}</dd>
            {% endif %}
            {% if device.token %}
                <dt>API Token</dt>
                <dd class="token">
                    <span class="token-placeholder" v-if="!tokenVisible" v-on:click="showToken">click to show</span>
                    <span class="token" v-if="tokenVisible">{{ device.token }}</span>
                </dd>
            {% endif %}
        </dl>
    </section>

    <section id="writes">
        <h2>Write Queue</h2>
        {% for write in device.writes.all %}
            <div class="write">{{ write.tag }}</div>
        {% empty %}
            <div class="write empty">(no writes queued)</div>
        {% endfor %}
    </section>

{% endblock content %}